### ISSUE TITLE
Using ExtJS CMD to build NPM Webpack modules?

### ISSUE THREAD

**Issue by maciej-zabielski** [dongryphon/extjs-webpack#1]
Hi Don, 

It's interesting to see Ext moving towards "open tooling". 
Today we use multi app workspace with a bit messy CMD packages, multiple themes and a lazy-loading. 
Migrating this to open tooling is not supported ("upgrading multi-application workspaces is not yet supported" error).

Actually we do not need to build Ext app using Webpack, but we need to use npm packages somehow in our app. These packages have vast number of dependencies and are basically unusable before "bundling" done by webpack.
 
Do you think is possible to hook up webpack bundling into CMD build process, so that a bundle is created by webpack  (from required nmp packages), so that CMD can pick it up as regular resources and further bundle them into app.js?

Or am I missing some obvious way of doing this? :) Maybe there is some way of "building a package into standalone bundle" outside of Ect build process? I could then add the resulting file to our ExtJS project. 

Thanks for any tips
Maciej

**Comment by vadimpopa** [comment]
Hey @maciej-zabielski , you can call any node process (including a webpack script ) in CMD, take a look here for some ideas: https://gist.github.com/vadimpopa/612974bc0cf7f5bca64670afae247aca

**Comment by maciej-zabielski** [comment]
hi @vadimpopa, thanks :) It's still a bit confusing for me... sorry for the lame questions :)

so yes, I could use build.xml to trigger some webpack job. 
But I'm not sure how to build npm package to a standalone resource within ExtJS ecosystem so to speak - I think that would be the easiest way to list all required packages somewhere and then compile them into one bundle. 

To my very limited knowledge about webpack a sample app would work this way (without Ext)
- we create an app that is also a package with package.json and webpack.config.js
- node is initialized and adds node_modules
- we also have our src folder with our script e.g. index.js and template index.html
- in our src we can use **import** {....} from "@provider/package";

when I build this using **npm run build** it will create a output folder with bundle.js that includes my script file and all dependencies listed via imports.

Now if we have Ext app that is transpiled and bundeled using Sencha Cmd, how could we use "mix" this with webpack build to take care of the **import** alone and leave Ext code aside - but I gess this is solved somehow in "open-tooling" from Sencha. I think I will try to generate a sample next-gen webpack enabled Sencha app, even thou they do not support multi app workspaces. Im using a separate mobile app with modern toolkit and separate classic app, but they share a lot of code using CMD packages. 

So I think there are two options in general
- create some sort of "sub project" for NPM modules under Ext workspace, bulit it in a way that makes the output available to Ext built process 
- have a NPM/Webpack enabled ExtJS app that can handle imports used anywhere in the Ext code. 

The latter is provided by sencha open-tooling that we do not have access to (multi app workspace...)

**Comment by vadimpopa** [comment]
I haven't used "open-tooling" and cannot suggest or comment anything. We use Webpack with Modern without CMD and we don't have any issues with these both worlds (Ext and npm packages).

**Comment by dongryphon** [comment]
I got a ping recently regarding this project and noticed this issue. To be clear, this project attempts to replace Cmd not be used as part of its build process. The idea is to read the Cmd definition files (`workspace.json`, `app.json`, etc) and enable file-level bundling in webpack or potentially other bundling tools.

If anyone is interested in furthering that goal, please open separate tickets and perhaps mention me on them as I (obviously) don't monitor this repo closely. I would love to have this piece working as I still use extjs but just haven't had the ambition to pursue it for some time.
